# Generated by Django 6.0.6 on 2026-06-18 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.CharField(choices=[('encryption', 'Fernet Encryption'), ('anonymization', 'Anonymization'), ('masking', 'Data Masking'), ('differential_privacy', 'Differential Privacy')], max_length=50)),
                ('original_record_count', models.IntegerField()),
                ('processed_record_count', models.IntegerField()),
                ('processing_time_seconds', models.FloatField()),
                ('utility_score', models.FloatField(help_text='Data utility preserved after privacy technique (0-1)')),
                ('privacy_score', models.FloatField(help_text='Privacy strength of the technique (0-1)')),
                ('output_sample', models.JSONField(blank=True, help_text='Sample of processed output', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_results', to='organisations.organisation')),
            ],
        ),
    ]
