# Generated by Django 6.0.6 on 2026-06-19 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('privacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymizedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_criteria', models.CharField(help_text="e.g. 'diagnosis=Hypertension'", max_length=255)),
                ('record_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_anonymized_datasets', to='organisations.organisation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_anonymized_datasets', to='organisations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='AnonymizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymized_label', models.CharField(help_text="e.g. 'Patient_001'", max_length=100)),
                ('age_range', models.CharField(help_text="e.g. '30-40'", max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('diagnosis', models.CharField(max_length=255)),
                ('medication', models.CharField(max_length=255)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='privacy.anonymizeddataset')),
            ],
        ),
        migrations.CreateModel(
            name='SharedEncryptedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id_reference', models.CharField(help_text='Original patient_id at sender side, for reference', max_length=100)),
                ('encrypted_payload', models.TextField(help_text='Fernet-encrypted JSON of the patient record')),
                ('encryption_key', models.CharField(help_text='Fernet key needed to decrypt this payload', max_length=255)),
                ('is_decrypted', models.BooleanField(default=False)),
                ('decrypted_at', models.DateTimeField(blank=True, null=True)),
                ('decrypted_payload', models.JSONField(blank=True, help_text='Plaintext patient data after decryption', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_encrypted_records', to='organisations.organisation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_encrypted_records', to='organisations.organisation')),
            ],
        ),
    ]
