# Generated by Django 6.0.6 on 2026-06-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0002_anonymizeddataset_anonymizedrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedencryptedrecord',
            name='key_retrieved',
            field=models.BooleanField(default=False, help_text='True once receiver has fetched the key via the dedicated endpoint'),
        ),
    ]
