# Generated by Django 6.0.6 on 2026-08-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0003_sharedencryptedrecord_key_retrieved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedencryptedrecord',
            name='encryption_key',
        ),
        migrations.RemoveField(
            model_name='sharedencryptedrecord',
            name='key_retrieved',
        ),
        migrations.RemoveField(
            model_name='sharedencryptedrecord',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='sharedencryptedrecord',
            name='sender',
        ),
        migrations.AddField(
            model_name='sharedencryptedrecord',
            name='encrypted_session_key',
            field=models.TextField(default='', help_text='RSA-encrypted one-time session key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedencryptedrecord',
            name='sender_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedencryptedrecord',
            name='sender_url',
            field=models.URLField(default='', help_text="Base URL of the sender's server, e.g. http://127.0.0.1:8000"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedencryptedrecord',
            name='signature',
            field=models.TextField(default='', help_text="Sender's digital signature over the plaintext"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedencryptedrecord',
            name='signature_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sharedencryptedrecord',
            name='decrypted_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sharedencryptedrecord',
            name='encrypted_payload',
            field=models.TextField(help_text='AES-encrypted patient data'),
        ),
        migrations.AlterField(
            model_name='sharedencryptedrecord',
            name='patient_id_reference',
            field=models.CharField(max_length=100),
        ),
    ]
