# Generated by Django 6.0.6 on 2026-08-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0004_remove_sharedencryptedrecord_encryption_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymizeddataset',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='anonymizeddataset',
            name='sender',
        ),
        migrations.AddField(
            model_name='anonymizeddataset',
            name='sender_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anonymizeddataset',
            name='sender_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anonymizedrecord',
            name='age_range',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='anonymizedrecord',
            name='anonymized_label',
            field=models.CharField(max_length=100),
        ),
    ]
