# Generated by Django 6.0.6 on 2026-08-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='private_key',
            field=models.TextField(blank=True, help_text="RSA private key, NEVER leaves this server's own database", null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='public_key',
            field=models.TextField(blank=True, help_text='RSA public key, safe to share with other organisations', null=True),
        ),
    ]
