# Generated by Django 6.0.6 on 2026-08-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_anonymizeddataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymizeddataset',
            name='to_hospital',
        ),
        migrations.AddField(
            model_name='anonymizeddataset',
            name='to_hospital_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anonymizeddataset',
            name='to_hospital_url',
            field=models.URLField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
