# Generated by Django 6.0.6 on 2026-06-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, default='0000000000', max_length=20),
        ),
    ]
