# Generated by Django 6.0.6 on 2026-06-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('patients', '0002_patient_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('organisation', 'patient_id')},
        ),
    ]
