# Generated by Django 6.0.6 on 2026-07-22 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['patient_id']},
        ),
    ]
